version: "3.2"

services:
  test_postgres:
    container_name: "test-postgres"
    image: "postgres:13-alpine"
    environment:
      POSTGRES_MULTIPLE_DATABASES: "${INTEGRATION_PG_DATABASE}"
      POSTGRES_USER: "${INTEGRATION_PG_USER}"
      POSTGRES_PASSWORD: "${INTEGRATION_PG_PASSWORD}"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - testnet
    volumes:
      - type: bind
        source: ./docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
        read_only: true
  redis:
    image: redis:6-alpine
    networks:
      - testnet
    ports:
      - 6379:6379

networks:
  testnet:
